version: "3.2"

services:
  nox:
    hostname: nox
    image: 927technology/qbittorrent-nox:0.6
    environment:
      - nox_password=YI5Fl0hPYiaelcUlX/d+yA==:23cCRFRcY99l+Pwd4pjYJCqYP8Fn/++yUg4df0poMCpD3407WdWtJHEGJhpNktbs+AKuqZqNIHdmheZu8euHeQ==
      - nox_ipaddr=*
      - nox_port=8080
      - nox_username=admin
    ports:
      - 8080:8080
    volumes:
      - ./torrent:/torrent
